version: "3.2"

services:
  web:
    build: .
    image: cbb
    ports:
      - 5000:5000
    volumes:
      - .:/src
    command: yarn dev
    environment:
      - MONGO_URI=mongodb://claw_ban_bot:supersecretpassword@mongo/claw_ban_bot

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: claw_ban_bot
      MONGO_INITDB_ROOT_PASSWORD: supersecretpassword

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: claw_ban_bot
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecretpassword
